boardgamers/gaia-project

engine/src/player.ts, viewer/src/components/BoardAction.spec.ts, viewer/src/components/BoardAction.vue, viewer/src/components/Game.vue, viewer/src/components/PlayerBoard/BuildingGroup.vue, viewer/src/components/PlayerBoard/Info.vue, viewer/src/components/PlayerInfo.vue, viewer/src/components/ResearchTile.vue, viewer/src/components/SpaceHex.vue, viewer/src/components/SpecialAction.vue, viewer/src/components/Token.vue, viewer/src/logic/recent.spec.ts, viewer/src/logic/recent.ts, viewer/src/store.ts
=> mark recent moves in player area and research board

viewer/src/components/PlayerBoard/BuildingGroup.vue
fixes 
of https://www.boardgamers.space/game/deep-mind-2
=> fix recent buildings

viewer/src/logic/charts.ts
=> fix tooltip

viewer/src/logic/charts.ts
=> add player total to bar chart

viewer/src/components/PlayerBoard/Info.vue, viewer/src/components/PlayerInfo.vue, viewer/src/components/ResearchTile.vue, viewer/src/components/SpaceHex.vue, viewer/src/components/SpaceMap.vue, viewer/src/components/Token.vue, viewer/src/logic/recent.ts, viewer/src/store.ts
=> fix bugs related to css class casing

viewer/src/logic/charts.ts
Fixes #28 
and show final scoring separately for ended games
=> don't could bids twice

viewer/src/components/PlayerInfo.vue
🐛 fix faction dialog
step colors were missing
=> 🐛 fix faction dialog

viewer/src/components/PlayerInfo.vue, viewer/src/store.ts
=> show recent player actions

viewer/src/components/Charts.vue, viewer/src/components/Game.vue, viewer/src/logic/chart.spec.ts, viewer/src/logic/charts.ts, viewer/src/logic/simple-charts.ts, viewer/src/logic/victory-point-charts.ts
=> add building, research charts

viewer/src/components/Charts.vue, viewer/src/logic/charts.ts, viewer/src/logic/simple-charts.ts
=> add planets / terraformings charts

viewer/src/assets/resources/table.svg, viewer/src/components/Charts.vue
=> table view for charts

viewer/src/components/Charts.vue, viewer/src/logic/chart-factory.ts, viewer/src/logic/charts.ts, viewer/src/logic/simple-charts.ts, viewer/src/logic/victory-point-charts.ts
=> cleanup_charts

engine/src/auto-charge.spec.ts, engine/src/auto-charge.ts, engine/src/engine.spec.ts, engine/src/player.ts, engine/wrapper.spec.ts, engine/wrapper.ts
=> new auto-charge mode: "always ask"

engine/src/available-command.ts, engine/src/engine.ts, engine/src/factions.spec.ts, engine/src/factions.ts, engine/src/player.ts, engine/src/tiles/boosters.spec.ts, viewer/src/components/AdvancedLog.vue, viewer/src/components/BoardAction.vue, viewer/src/components/Game.vue, viewer/src/components/Planet.vue, viewer/src/components/PlayerCircle.vue, viewer/src/components/SpaceHex.vue, viewer/src/data/index.ts, viewer/src/graphics/utils.ts, viewer/src/logic/recent.spec.ts, viewer/src/logic/recent.ts, viewer/src/self-contained.ts, viewer/src/store.ts
log placement can also be controlled in a reference - had to change the type to `boolean | string`
=> show returned booster in log / colorize log

engine/package.json, engine/pnpm-lock.yaml, engine/src/engine.spec.ts, engine/src/engine.ts, engine/tsconfig.json
Now to test the version with which the game was created, one can do:
```
import compare from "semver-compare"
class Engine {
doSomeStuff() {
if (compare(this.version ?? "0", "4.6.10") <= 0) {
// old behavior
} else {
// new behavior
}
}
}
```
When on BGS we decide to do a major breaking change, we can create a brand new version of the game there (currently at 2) and remove all the legacy code in the engine
=> 🚩 (engine) Store engine version metadata in JSON

viewer/src/components/Token.vue
See https://forum.boardgamers.space/topic/179/ui-is-extremely-slow/6
=> 💫 (viewer) Disable spin animation on tokens

engine/index.ts, engine/src/engine.ts, engine/src/events.ts, engine/src/faction-boards/ambas.ts, engine/src/faction-boards/baltaks.ts, engine/src/faction-boards/bescods.ts, engine/src/faction-boards/firaks.ts, engine/src/faction-boards/geodens.ts, engine/src/faction-boards/gleens.ts, engine/src/faction-boards/hadsch-hallas.ts, engine/src/faction-boards/index.ts, engine/src/faction-boards/itars.ts, engine/src/faction-boards/ivits.ts, engine/src/faction-boards/lantids.ts, engine/src/faction-boards/nevlas.ts, engine/src/faction-boards/taklons.ts, engine/src/faction-boards/terrans.ts, engine/src/faction-boards/types.ts, engine/src/faction-boards/xenos.ts, engine/src/factions.ts, engine/src/player.ts, viewer/src/components/Commands.vue, viewer/src/components/PlayerBoard/BuildingGroup.vue, viewer/src/components/PlayerInfo.vue, viewer/src/data/factions.ts, viewer/src/data/logTests/itars/all.json, viewer/src/logic/charts.ts, viewer/src/logic/recent.ts, viewer/src/logic/victory-point-charts.ts, viewer/src/self-contained.ts
=> balanced_factions

engine/src/auto-charge.spec.ts, engine/src/auto-charge.ts
=> 🐛 (engine) Fix taklons autodecline

engine/src/available-command.spec.ts, engine/src/available-command.ts, engine/src/engine.spec.ts, engine/src/engine.ts, engine/src/random-factions.spec.ts, viewer/src/components/Commands.vue, viewer/src/self-contained.ts
=> Random factions

viewer/src/components/PlayerBoard/Info.vue, viewer/src/components/PlayerBoard/PowerBowls.vue
Finally, I can finish a game without getting a headache :wink:
=> No power income in r6

engine/src/auto-charge.spec.ts, engine/src/auto-charge.ts, viewer/src/data/building.ts, viewer/src/logic/commands.ts
=> auto_charge

viewer/src/components/Commands.vue, viewer/src/logic/commands.ts
=> decline_research_warning

engine/src/available-command.ts, engine/src/player.spec.ts, engine/src/player.ts, viewer/src/components/Commands.vue, viewer/src/data/federations.ts, viewer/src/data/warnings.ts, viewer/src/logic/commands.ts, viewer/src/logic/simple-charts.ts
:sparkles: (all) warning for 
- gaia former in last round
- resource waste when choosing federation type
- choosing booster: resources would be lost during income phase
shortcuts for choosing federation type
=> new warnings

engine/index.ts, viewer/src/logic/commands.spec.ts, viewer/src/logic/commands.ts
charge income was handled both in resource warning as well as charge income warning
=> fix income warning

engine/src/engine.ts, engine/src/faction-boards/baltaks.ts, engine/src/faction-boards/bescods.ts, engine/src/faction-boards/firaks.ts, engine/src/faction-boards/geodens.ts, engine/src/faction-boards/gleens.ts, engine/src/faction-boards/hadsch-hallas.ts, engine/src/faction-boards/lantids.ts, engine/src/faction-boards/terrans.ts, engine/src/faction-boards/xenos.ts
beta variant as described in https://docs.google.com/document/d/1BKTUb7kByOgBp1cW65KipZINT0InjGo0xxc3cZTs1Js/edit#
=> bata variant

engine/src/cost.ts, engine/src/engine.spec.ts, engine/src/engine.ts, engine/src/faction-boards/taklons.spec.ts, engine/src/player-data.ts, engine/src/player.ts, engine/wrapper.spec.ts, viewer/src/data/logTests/itars/all.json, viewer/src/data/logTests/itars/recent.json, viewer/src/self-contained.ts
prevent illegal use of step action with gaia planet
=> prevent illegal use of step action with gaia planet

engine/src/available-command.spec.ts, engine/src/available-command.ts, engine/src/cost.spec.ts, engine/src/cost.ts, engine/src/engine.ts, engine/src/player.spec.ts, engine/src/player.ts, engine/src/tiles/boosters.spec.ts, engine/wrapper.ts, viewer/src/components/Commands.vue, viewer/src/components/Wrapper.vue, viewer/src/logic/chart-factory.ts, viewer/src/logic/chartTests/adv-tech-pass/advanced-tech-tiles.json, viewer/src/logic/chartTests/adv-tech-pass/test-case.json, viewer/src/logic/chartTests/all-families/advanced-tech-tiles.json, viewer/src/logic/charts.ts, viewer/src/logic/simple-charts.ts, viewer/src/self-contained.ts
=> make replay more permissive

engine/src/faction-boards/bescods.ts, engine/src/faction-boards/firaks.ts, engine/src/faction-boards/geodens.ts, engine/src/faction-boards/gleens.ts, engine/src/faction-boards/index.ts, engine/src/faction-boards/terrans.ts, engine/src/faction-boards/types.ts, engine/src/player.ts, viewer/src/components/Commands.vue, viewer/src/components/PlayerBoard/BuildingGroup.vue, viewer/src/components/Rules.vue
version: 2
- bescods: sci2
- firaks: eco1 instead of sci1
- geodens: terra2 + 2k
- gleens: nav3
- terrans: back to standard
=> beta variants balance update

viewer/src/logic/charts.ts, viewer/src/logic/victory-point-charts.ts
fix final scoring points and resource points for ended games
=> fix final scoring points and resource points for ended games

engine/index.ts, engine/src/player.ts, viewer/src/components/PlayerBoard/Info.vue
show the number of satellites left in the player board
=> show the number of satellites left in the player board

viewer/src/components/Commands.vue, viewer/src/components/MoveButton.vue, viewer/src/components/Planet.vue, viewer/src/components/PlayerBoard/BuildingGroup.vue, viewer/src/components/SpaceHex.vue, viewer/src/components/SpaceMap.vue, viewer/src/data/index.ts, viewer/src/logic/commands.ts, viewer/src/store.ts, viewer/src/stylesheets/planets.css
because it broke the custom federatoin selection
=> revert change for lost planet selection

viewer/src/components/MoveButton.vue
Not sure about it, please check it out!
=> 🐛 (viewer) Fix simulaneous show & click on same button

viewer/src/logic/charts/testdata/beta2-initial-research-vp/test-case.json, viewer/src/logic/charts/testdata/beta2-initial-research-vp/victory-points.json, viewer/src/logic/charts/victory-point-charts.ts
Fixes https://github.com/boardgamers/gaia-project/issues/189
=> VP for inital research

viewer/src/launcher.ts
Fix https://github.com/boardgamers/gaia-project/issues/190
=> 🐛 (viewer) Do not reset move when settings are changed

engine/wrapper.ts
This will enable testing viewer against the remote backend
=> ✨ (engine) Better `logSlice` implementation

viewer/src/components/Commands.vue, viewer/src/components/FactionWheel.vue, viewer/src/logic/commands.ts
=> show faction initial in faction wheel

engine/src/federation.ts, engine/src/player.ts
Fixes https://github.com/boardgamers/gaia-project/issues/208
=> fix ivits federation check

engine/index.ts, engine/src/available-command.ts, engine/src/engine.ts, engine/src/enums.ts, engine/src/map.ts, engine/src/setup.ts, viewer/src/components/MoveButton.vue, viewer/src/components/ScoringBoard.vue, viewer/src/components/Sector.vue, viewer/src/components/TechTile.vue, viewer/src/data/index.ts, viewer/src/data/log.ts, viewer/src/data/round-scorings.ts, viewer/src/logic/buttons/setup.ts, viewer/src/logic/commands.ts, viewer/src/self-contained.ts
=> add custom board setup

viewer/src/components/Commands.vue, viewer/src/components/SpaceMap.vue, viewer/src/data/index.ts, viewer/src/logic/buttons/setup.ts, viewer/src/logic/commands.ts, viewer/src/store.ts
=> custom board setup

engine/src/engine.ts, engine/wrapper.ts, viewer/src/logic/charts/resource-counter.spec.ts, viewer/src/logic/recent.ts
let the creator do the board setup
=> let the creator do the board setup

engine/src/engine.ts, engine/src/setup.ts
=> simplify random setup

viewer/src/logic/buttons/autoClick.ts, viewer/src/logic/buttons/buildings.ts, viewer/src/logic/buttons/commands.ts, viewer/src/logic/buttons/conversion.ts
fix place lost planet / swap PI
=> fix place lost planet / swap PI

viewer/src/components/Commands.vue
=> disable auto-click

viewer/src/components/Commands.vue
will not be deployed to everyone
=> test "always" better, then re-enable

engine/src/available-command.ts, viewer/src/logic/buttons/buildings.ts, viewer/src/logic/buttons/commands.ts
Fixes https://github.com/boardgamers/gaia-project/issues/226
=> fix swap pi

engine/src/enums.ts, engine/src/events.spec.ts, engine/src/events.ts, engine/src/player.ts, engine/src/tiles/techs.ts, old-ui/src/data/event.ts, viewer/src/components/TechContent.vue, viewer/src/data/event.ts
=> 🐛 (engine) Federation impossible to make when covering 4pw tech tile

engine/src/player-data.ts
=> fix deployed ships

engine/src/auto-charge.spec.ts, engine/src/auto-charge.ts, engine/src/player.ts, engine/wrapper.ts
auto charge based on target power
=> auto charge based on target power

engine/src/faction-boards/geodens.ts, engine/src/faction-boards/gleens.ts
Fixes https://github.com/boardgamers/gaia-project/issues/312
=> fix colony for gleens and geodens

engine/src/auto-charge.spec.ts, engine/src/auto-charge.ts
(engine) auto charge based on target power was broken
=> (engine) auto charge based on target power was broken

engine/src/move/auto.ts
=> 🚑 Gimp autocharge while waiting for fix

engine/src/faction-boards/nevlas.spec.ts, engine/src/player-data.ts
Fixes https://github.com/boardgamers/gaia-project/issues/319
=> fix nevla final resource handling
